import { Project } from "./../../interfaces/index";

export const Projects: Project[] = [
    {
        img: "/image/todo.png",
        title: "TO DO List",
        link: "https://kudryakovsergeytodoangular.web.app/",
        id: 1,
        skill: "HTML, CSS, JS, TS, ANGULAR ",
    },
    {
        img: "/image/super.png",
        title: "Super Hero Game",
        link: "https://herokudryakov.web.app/",
        id: 2,
        skill: "HTML, CSS, JS, TS, ANGULAR ",
    },
    {
        img: "/image/Evklid.png",
        title: "Evklid. Builders' site",
        link: "https://evclid-5ca7a.web.app/",
        id: 3,
        skill: "HTML, CSS, JS, TS, ANGULAR ",
    },
    {
        img: "/image/balloons.png",
        title: "Balloons. Air balloons site",
        link: "https://sikey747.github.io/Balloon/home.HTML,",
        id: 4,
        skill: "HTML, CSS, JS, GULP ",
    },
    {
        img: "/image/smart.png",
        title: "SmartSpace, Estate Deals",
        link: "https://sikey747.github.io/SmartSpace/",
        id: 5,
        skill: "HTML, CSS, JS, GULP ",
    },
    {
        img: "/image/marceting.png",
        title: "Omarketing Marketing Comp",
        link: "https://sikey747.github.io/omarketing/",
        id: 6,
        skill: "HTML, CSS, JS, GULP ",
    },
    {
        img: "/image/marcho.png",
        title: "marcho",
        link: "https://sikey747.github.io/marcho/home.html",
        id: 7,
        skill: "HTML, CSS, JS, GULP ",
    },
    {
        img: "/image/restoran.png",
        title: "Gericht Restaurant",
        link: "https://sikey747.github.io/gericht-dist/",
        id: 8,
        skill: "HTML, CSS, JS, GULP ",
    },
    {
        img: "/image/metavers.png",
        title: "metavers",
        link: "https://metaversus-code.vercel.app/",
        id: 9,
        skill: "REACT, FRAME MOTION, HTML, CSS, JS, NEXT JS",
    },
    {
        img: "/image/Spotify.png",
        title: "SpotifyFinedArtistName",
        link: "https://sikey747.github.io/SpotifyFindeArtistName/",
        id: 10,
        skill: "REACT, FRAME MOTION, HTML, CSS, JS, VITE, REACT QUERY, ZUSTAND, TAILWIND, AXIOS",
    },
    {
        img: "/image/eshop.png",
        title: "EShop",
        link: "https://e-shop-lovat-nine.vercel.app/",
        id: 11,
        skill: "REACT, TAILWIND, FRAME MOTION, HTML, CSS, JS, NEXT JS, REACT QUERY, AUTH, AXIOS, PRISMA, SWIPER",
    },
    {
        img: "/image/Pizza.png",
        title: "PizzaReact",
        link: "https://sikey747.github.io/PizzaReact",
        id: 12,
        skill: "REACT, HTML, SCSS, TS, REACT QUERY, AXIOS, REDUX",
    },
    // {
    //     img: "/image/Abz.png",
    //     title: "Abz",
    //     link: "https://sikey747.github.io/Abz/",
    //     id: 13,
    //     skill: "REACT, HTML, SCSS, TS, REACT QUERY, AXIOS, ZUSTAND",
    // },
];
